default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tiendita_development

test:
  <<: *default
  database: tiendita_test

production:
  <<: *default
  database: tiendita_production
  username: tiendita
  password: <%= ENV['TIENDITA_DATABASE_PASSWORD'] %>
